[package]
name = "lfg"
version = "0.1.0"
authors = ["Andrew Merenbach <andrew@merenbach.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
derive_builder = "0.10"
